name: Sync services
on: 
  repository_dispatch:

jobs:
  Sync-services:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Prod Env  
        uses: actions/checkout@v3 
        with:
          token: ${{ secrets.PELICAN_ENV_SYNC_TRIGGER_TOKEN }}

      - name: Set branch name
        run: 
          echo "BRANCH_NAME=feature/sync-image-tag-${{ github.event.client_payload.repository }}-$(date +'%FT%H-%M')-short-sha-${{ github.event.client_payload.short_sha }}" >> $GITHUB_ENV
      
      - name: Set path to values file and helmfile
        run: |
          # Example of PATH_TO_VALUES: deploy/values-ui.yaml.gotmpl 
          echo "PATH_TO_VALUES=${{ github.event.client_payload.path_to_values }}" >> $GITHUB_ENV
          # Example of PATH_TO_HELMFILE: deploy/helmfile.yaml
          echo "PATH_TO_HELMFILE=${{ github.event.client_payload.path_to_helmfile }}" >> $GITHUB_ENV

      # double quotes and new lines in multiline commit message breaks the sync workflow
      # using json to file trick that replaces double quotes and new lines with \" and \n
      # -e is used to enable interpretation of the following backslash escapes (e.g \n)
      - name: Write commit message to file
        run: 
          echo -e ${{ toJson(github.event.client_payload.commit_message) }} > commit_message.txt

        # We tried to use yq to change the image tag, but in the values files for helmfile we have non-yaml code that yq can`t parse or ignore
        # so for that reason we use Stream EDitor which can find needeed string using regular expressions and change it to a new value
        # The -i flag is needed to write new image tag directly to values file
      - name: Write new image tag to values
        run: |
          sed -i "0,/tag:.*/s//tag: \"${{ github.event.client_payload.image_tag }}\"/" $PATH_TO_VALUES

      - name: Write new tag to helmfile
        run: |
          sed -i "0,/git+https:\/\/github.com\/TourmalineCore\/${{ github.event.client_payload.service_name }}.git?ref=.*/s//git+https:\/\/github.com\/TourmalineCore\/${{ github.event.client_payload.service_name }}.git?ref=${{ github.event.client_payload.sha }}/" $PATH_TO_HELMFILE
          sed -i "0,/git::https:\/\/github.com\/TourmalineCore\/${{ github.event.client_payload.service_name }}.git@\/ci\/values.yaml?ref=.*/s//git::https:\/\/github.com\/TourmalineCore\/${{ github.event.client_payload.service_name }}.git@\/ci\/values.yaml?ref=${{ github.event.client_payload.sha }}/" $PATH_TO_HELMFILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name github-actions[bot]
          # 41898282 is id of GitHub Actions Bot that was taken from GitHub API: https://api.github.com/users/github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          git checkout -b $BRANCH_NAME master

          git add $PATH_TO_VALUES

          git add $PATH_TO_HELMFILE

          git commit -F commit_message.txt
          
          git push origin $BRANCH_NAME

      - name: Set PR title
        run: 'echo "PR_TITLE=sync: ${{ github.event.client_payload.repository }} image tag" >> $GITHUB_ENV' 
        
      - name: Create PR
        run: gh pr create -B master -H $BRANCH_NAME --title "${{ env.PR_TITLE }}" -F commit_message.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Approve PR
        run: gh pr review $BRANCH_NAME -a
        env:
          GITHUB_TOKEN: ${{ secrets.PELICAN_ENV_SYNC_TRIGGER_TOKEN }}

      - name: Merge PR
        run: gh pr merge $BRANCH_NAME --merge --subject "${{ env.PR_TITLE }}" -F commit_message.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
